title: 周新然的个人主页
page-top-title: Xinran Zhou
top-section-bg-text: Fintech
home-subtitle: Xinran Zhou&ensp;|&ensp;周新然
email: zhouxinran5561@163.com
copyright-text: '&copy; Xinran Zhou 2024-2026. All Rights Reserved.'
